# Generated by Django 6.0.5 on 2026-05-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('password', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
