# Generated by Django 6.0.5 on 2026-05-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
