# Generated by Django 6.0.5 on 2026-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_commit_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='password',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
